### ISSUE TITLE
plugin is not working

### ISSUE THREAD

**Issue by ruslanshelar** [connorshea/vscode-ruby-test-adapter#22]
Hello everybody!
I installed  Ruby Test Explorer but nothing is working. When I start VS Code I get next error:

Command failed: rspec --require c:\Users\shredder\.vscode\extensions\connorshea.vscode-ruby-test-adapter-0.6.0\custom_formatter.rb --format CustomFormatter --order defined --dry-run 

Source: Ruby Test Explorer

And this warning:
Ruby Test Explorer failed to find an RSpec test suite. Make sure RSpec is installed and your configured RSpec command is correct.

Settings of Ruby Test Explorer

    "rubyTestExplorer.rspecCommand": "rspec",
    "rubyTestExplorer.rspecDirectory": 
    "C:\\Users\\shredder\\VisualStudioCodeProjects\\<project_name\\spec",
    "rubyTestExplorer.logpanel": true

And there is nothing in Test menu
![image](https://user-images.githubusercontent.com/32563167/62860748-dfe20e00-bd09-11e9-9a6c-ad89ddda5c17.png)

- `vscode-ruby-test-adapter` version: 0.6.0
- Ruby version: 2.6.3
- VS Code version: 1.37.0
- Operating System: Windows 10
- RSpec version: rspec-core 3.8.2

Can you help me, please?

**Comment by connorshea** [comment]
Hi! Do you have any log messages in the Developer Tools Console (Ctrl+Shift+P to open the command palette and then use "Developer: Toggle Developer Tools") or the Output panel (Ctrl+Shift+P to open the command palette and use "View: Toggle Output", then click the dropdown in the Output panel and switch to "Ruby Test Explorer Log") that seem relevant to the issue?

Also, do you have Ruby installed locally on Windows or in the Windows Subsystem for Linux?

**Comment by ruslanshelar** [comment]
Hi! I have ruby installed locally on Windows but I have tried to do same from WSL and had the same problem.
Yes I have the next error  in the Developer Tools Console
```
ERR Command failed: rspec --require c:\Users\shredder\.vscode\extensions\connorshea.vscode-ruby-test-adapter-0.6.0\custom_formatter.rb --format CustomFormatter --order defined --dry-run
SimpleCov failed with exit 1: Error: Command failed: rspec --require c:\Users\shredder\.vscode\extensions\connorshea.vscode-ruby-test-adapter-0.6.0\custom_formatter.rb --format CustomFormatter --order defined --dry-run
SimpleCov failed with exit 1
	at ChildProcess.exithandler (child_process.js:299:12)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:962:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by vucinjo** [comment]
I got the following error when I run single test:

```
stack trace: TypeError: Cannot read property 'status' of undefined
    at RspecTests.handleStatus (/Users/vucinjo/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.6.0/out/rspecTests.js:95:18)
    at RspecTests.<anonymous> (/Users/vucinjo/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.6.0/out/tests.js:282:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/vucinjo/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.6.0/node_modules/tslib/tslib.js:104:62)
/Applications/Visual…kbench.main.js:1449   ERR Cannot read property 'status' of undefined: TypeError: Cannot read property 'status' of undefined
    at RspecTests.handleStatus (/Users/vucinjo/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.6.0/out/rspecTests.js:95:18)
    at RspecTests.<anonymous> (/Users/vucinjo/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.6.0/out/tests.js:282:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/vucinjo/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.6.0/node_modules/tslib/tslib.js:104:62)

```

**Comment by williamhatch** [comment]
@ruslanshelar same issue as me. Mine is Mac.

**Comment by williamhatch** [comment]
@ruslanshelar OK I can run now. Just add 
gem 'rspec-rails','3.8.2'
  gem 'rspec-core','3.8.2'
  gem 'minitest'

to the test env. Make sure rspec-core is 3.8.2. (Seems 3.5.2 doesnt work)

**Comment by rezammalik** [comment]
Ran into the same issue. I have rspec 3.8.2 installed. 

> /Users/rezamalik/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.6.0/custom_formatter.rb --format CustomFormatter --order defined --dry-run
: Error: Command failed: bundle exec rspec --require /Users/rezamalik/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.6.0/custom_formatter.rb --format CustomFormatter --order defined --dry-run

	at ChildProcess.exithandler (child_process.js:299:12)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:962:16)
	at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)

**Comment by tdegrunt** [comment]
This plugin looks very useful, I'd like to use it too, but having problems.

It seems $EXT_DIR and/or $TESTS_DIR are not set? 
If I set them manually and execute the command myself it does something:

EXT_DIR=~/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.6.0/ruby/ TESTS_DIR=./test RAILS_ENV=test bundle exec rake -R $EXT_DIR vscode:minitest:list

But bails out on finding duplicate tests (which we don't have).

**Comment by tdegrunt** [comment]
Additional to the above, when I don't run this in a workspace but in a project itself, things are starting to work. I had to remove one duplicate named test and then it all just works.

**Comment by connorshea** [comment]
Does anyone have a repo I could look at to reproduce this issue? I’m on RSpec 3.8 and my Rails app works fine, so I’m not sure what’s causing the problems.

**Comment by connorshea** [comment]
@vucinjo were you using the Remote extensions, and what version of VS Code?

**Comment by avstudio** [comment]
@connorshea No. I don't have remote extensions installed. Here are the version details:
Version: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by alexandrubisa** [comment]
I had the same bug on MacOS and solved it by:
- Updating the gemfile (which forced an old version of rspec, I now use " gem "rspec", "~> 3.9.0" ")
- Updated the gem itself using gem update
- Adding the following in settings.json (I use rbenv):

`"rubyTestExplorer.testFramework": "auto",
    "rubyTestExplorer.rspecCommand": "/Users/<username>/.rbenv/shims/bundle exec rspec",
    "rubyTestExplorer.rspecDirectory": "./spec/"`

**Comment by george-norris-salesforce** [comment]
Not working for me either

**Comment by mtancoigne** [comment]
@Duartemartins Same here:

```log
[2021-12-24 14:23:32.544] [exthost] [info] ExtensionService#_doActivateExtension connorshea.vscode-ruby-test-adapter, startup: true, activationEvent: 'workspaceContains:**/Rakefile,**/Gemfile,**/*.rb'
[2021-12-24 14:23:32.554] [exthost] [error] Activating extension connorshea.vscode-ruby-test-adapter failed due to an error:
[2021-12-24 14:23:32.554] [exthost] [error] Error: Cannot find module '/home/me/.vscode-oss/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/out/src/main.js'
Require stack:
- /usr/share/codium/resources/app/out/vs/loader.js
- /usr/share/codium/resources/app/out/bootstrap-amd.js
- /usr/share/codium/resources/app/out/bootstrap-fork.js
```
I checked the filesystem and `/home/me/.vscode-oss/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/out/src/main.js` does not exist. The `out` dir does not exist.

**Comment by mtancoigne** [comment]
Well, i rebuilt the plugin and it seems to do the trick (at least tests are showing):

```sh
cd ~/.vscode-oss/extensions/
rm -rf connorshea.vscode-ruby-test-adapter-0.9.0
git clone git@github.com:connorshea/vscode-ruby-test-adapter.git connorshea.vscode-ruby-test-adapter-0.9.0
cd connorshea.vscode-ruby-test-adapter-0.9.0
bin/setup
npx tsc
```
