### ISSUE TITLE
Failed to run specs with rspec 3.5.4 and ruby 2.3.8p459

### ISSUE THREAD

**Issue by dreamingblackcat** [connorshea/vscode-ruby-test-adapter#45]
### Your environment

- `vscode-ruby-test-adapter` version:
- Ruby version: 2.3.8p459
- VS Code version: 0.7.1
- Operating System:  OS X Catalina (v10.15.1)
- RSpec version: 3.5.4

### Expected behavior
Extension should load and run the specs.

### Actual behavior
It fails to load with the following output in the `Ruby Test Explorer Log` panel.
```
[2020-02-19 02:27:36.552] [ERROR] Error while finding RSpec test suite: Command failed: bundle exec rspec --require /Users/chanmyaesanhlaing/.vscode-insiders/extensions/connorshea.vscode-ruby-test-adapter-0.7.1/custom_formatter.rb --format CustomFormatter --order defined --dry-run

NoMethodError: undefined method `errors_outside_of_examples_count' for #<RSpec::Core::Notifications::SummaryNotification:0x00007f9a52c3dae0>
  /Users/chanmyaesanhlaing/.vscode-insiders/extensions/connorshea.vscode-ruby-test-adapter-0.7.1/custom_formatter.rb:37:in `dump_summary'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:201:in `block in notify'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:200:in `each'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:200:in `notify'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:179:in `block in finish'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:187:in `close_after'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:168:in `finish'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:79:in `report'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:87:in `run'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/bin/rspec:22:in `load'
  /Users/chanmyaesanhlaing/.rbenv/versions/2.3.8/bin/rspec:22:in `<top (required)>'
```

**Comment by connorshea** [comment]
I guess that method wasn't added to RSpec until 3.6: https://github.com/rspec/rspec-core/commit/c03c0f2062fbb420614e4d1559a8f4f6e7be88f3

3.6 is the earliest version supported by this extension and it's almost 3 years old. I'd recommend upgrading RSpec.

**Comment by dreamingblackcat** [comment]
@connorshea  Thank you for the prompt response. I upgraded to rspec 3.9 and it worked! 🎉
