### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by scarletsec** [connorshea/vscode-ruby-test-adapter#54]
Having an issue with the plugin finding the tests.  It's complaining about the rakefile missing from the `$EXT_DIR` which is set to `/root/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.7.1/ruby/`.

### VSCode Environment
Plugin is installed remotely into dev container running on Windows with Docker.  

- VSCode 1.49.2
- Ruby Test Explorer 0.7.1
- Test Explorer UI 2.19.1
- Ruby 0.27.0

### Ruby Test Explorer Log
```
[2020-09-26 22:21:45.171] [INFO] Loading Ruby tests...
[2020-09-26 22:21:45.171] [INFO] Loading Minitest tests...
[2020-09-26 22:21:45.171] [INFO] Getting a list of Minitest tests in suite with the following command: bundle exec rake -R $EXT_DIR vscode:minitest:list
[2020-09-26 22:21:45.485] [ERROR] Error while finding Minitest test suite: Command failed: bundle exec rake --trace -R $EXT_DIR vscode:minitest:list
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:698:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/usr/local/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

### Ruby version and gems installed
```
$ ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

$ bundle list | grep -e rake -e test-unit -e minitest -e rspec
  * minitest (5.14.2)
  * rake (13.0.1)
  * rspec-core (3.8.2)
  * rspec-support (3.8.3)
  * test-unit (3.3.6)
```

### Listing from the plugin's ruby directory
```
$ ls /root/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.7.1/ruby/
Gemfile  Rakefile  specs  vscode  vscode.rake
```

**Comment by Gee-Bee** [comment]
Experiencing the same problem with similar setup: extension v0.8.0 running in devcontainer on Linux host, rake v12.3.3, ruby v.2.6.6.

```sh
sh> echo $EXT_DIR
/root/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.8.0/ruby
sh> rake -R $EXT_DIR vscode:minitest:list
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```
