### ISSUE TITLE
Unable to debug specs

### ISSUE THREAD

**Issue by cec** [connorshea/vscode-ruby-test-adapter#58]
### Your environment

- `vscode-ruby-test-adapter` version: 0.8.0
- Ruby version: 2.3.8
- VS Code version: 1.51.1
- Operating System: Ubuntu 18.04 via WSL2 (Windows 10)
- RSpec version: 3.6.0

### Expected behavior
Selecting a rspec example group from the test explorer panel and clicking the debug icon should run the example group with debugging enabled.

### Actual behavior
I get an popup with the error: 

Error while debugging test: SyntaxError: Unexpected end of JSON input
Source: Test Explorer UI (Exension)

In the output panel, if I select `Ruby Test Explorer Log` I see the following when trying to debug geolocation_utils_spec.rb

````
[2020-11-23 09:02:23.505] [INFO] Debugging test(s) ["./spec/lib/geolocation_utils_spec.rb"] of /home/cec/core/ruby-projects/agendalugano
[2020-11-23 09:02:23.505] [INFO] Running Ruby tests ["./spec/lib/geolocation_utils_spec.rb"]
[2020-11-23 09:02:23.506] [INFO] Starting the debug session
[2020-11-23 09:02:23.506] [INFO] Running test file: /home/cec/core/ruby-projects/agendalugano/spec/lib/geolocation_utils_spec.rb
[2020-11-23 09:02:23.506] [INFO] Running command: rdebug-ide --host 127.0.0.1 --port 1234 -- $EXT_DIR/debug_rspec.rb --require /home/cec/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.8.0/custom_formatter.rb --format CustomFormatter '/home/cec/core/ruby-projects/agendalugano/spec/lib/geolocation_utils_spec.rb'
[2020-11-23 09:02:23.990] [DEBUG] [CHILD PROCESS OUTPUT] Fast Debugger (ruby-debug-ide 0.7.2, debase 0.2.4.1, file filtering is supported) listens on 127.0.0.1:1234
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] Uncaught exception: cannot load such file -- /debug_rspec.rb
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	/home/cec/.rvm/gems/ruby-2.3.8@agenda/bin/rdebug-ide:23:in `load'
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	/home/cec/.rvm/gems/ruby-2.3.8@agenda/bin/rdebug-ide:23:in `<main>'
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	/home/cec/.rvm/gems/ruby-2.3.8@agenda/bin/ruby_executable_hooks:24:in `eval'
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	/home/cec/.rvm/gems/ruby-2.3.8@agenda/bin/ruby_executable_hooks:24:in `<main>'
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] /home/cec/.rvm/gems/ruby-2.3.8@agenda/gems/ruby-debug-ide-0.7.2/lib/ruby-debug-ide.rb:106:in `debug_load': cannot load such file -- /debug_rspec.rb (LoadError)
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	from /home/cec/.rvm/gems/ruby-2.3.8@agenda/gems/ruby-debug-ide-0.7.2/lib/ruby-debug-ide.rb:106:in `debug_program'
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	from /home/cec/.rvm/gems/ruby-2.3.8@agenda/gems/ruby-debug-ide-0.7.2/bin/rdebug-ide:193:in `<top (required)>'
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	from /home/cec/.rvm/gems/ruby-2.3.8@agenda/bin/rdebug-ide:23:in `load'
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	from /home/cec/.rvm/gems/ruby-2.3.8@agenda/bin/rdebug-ide:23:in `<main>'
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	from /home/cec/.rvm/gems/ruby-2.3.8@agenda/bin/ruby_executable_hooks:24:in `eval'
[2020-11-23 09:02:24.368] [DEBUG] [CHILD PROCESS OUTPUT] 	from /home/cec/.rvm/gems/ruby-2.3.8@agenda/bin/ruby_executable_hooks:24:in `<main>'
[2020-11-23 09:02:24.372] [INFO] Child process has exited. Sending test run finish event.
[2020-11-23 09:02:24.403] [DEBUG] Parsing the below JSON:
[2020-11-23 09:02:24.403] [DEBUG] 
[2020-11-23 09:02:25.047] [INFO] Debug session ended
[2020-11-23 09:02:25.047] [INFO] Killing currently-running tests.
````

I apologize in advance if this is a stupid setup mistake on my end, but I'm new to VS Code as a IDE, since before I could work on a linux desktop and I used RubyMine.

This extensions is absolutely amazing! I can't thank you enough for it.

**Comment by dominikplsek** [comment]
I have the same issue. Here's a log from the Developer Tools if that's any help:
```
notificationsAlerts.ts:40 Error while debugging test: SyntaxError: Unexpected end of JSON input
onDidChangeNotification @ breadcrumbsModel.ts:39
(anonymous) @ breadcrumbsModel.ts:39
fire @ event.ts:584
addNotification @ notifications.ts:204
notify @ notificationService.ts:88
(anonymous) @ mainThreadLogService.ts:16
_showMessage @ mainThreadLogService.ts:16
$showMessage @ mainThreadLogService.ts:16
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:431
_receiveMessage @ ipc.net.ts:764
(anonymous) @ ipc.net.ts:624
fire @ event.ts:584
acceptChunk @ ipc.net.ts:174
(anonymous) @ ipc.net.ts:174
t @ ipc.net.ts:900
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
```

**Comment by wtaysom** [comment]
Can add that I have the same issue using Minitest instead of RSpec.

**Comment by wtaysom** [comment]
But then it went away presumably from auto-updates.

**Comment by StefanoDeVuono** [comment]
It's back!

Does anyone have specific instructions on how to debug the extension? I'd be happy to dig into this.

**Comment by connorshea** [comment]
@StefanoDeVuono the Contributing section should have everything you need, I think: https://github.com/connorshea/vscode-ruby-test-adapter#contributing

**Comment by tmlane** [comment]
I have this issue as well, with rspec

**Comment by lukesarnacki** [comment]
Hi! First of all, thanks for putting your work into this extension, it is awesome!

Sadly I have a similar issue but in my case it is not a server running (as mentioned in one of the previous answers). I am able to debug rspec using extension for Ruby but for test explorer I get this:

```
[2021-12-09 23:45:06.468] [INFO] Running command: rdebug-ide --host 127.0.0.1 --port 1234 -- $EXT_DIR/debug_rspec.rb --require /Users/me/.vscode/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/custom_formatter.rb --format CustomFormatter '/Users/me/projects/my-app/spec/services/metrics/my_spec.rb:33'
[2021-12-09 23:45:07.209] [DEBUG] [CHILD PROCESS OUTPUT] Fast Debugger (ruby-debug-ide 2.3.1, debase 2.3.2, file filtering is supported, block breakpoints supported, smart steps supported, obtaining return values supported, partial obtaining of instance variables supported) listens on 127.0.0.1:1234
[2021-12-09 23:45:09.635] [DEBUG] [CHILD PROCESS OUTPUT] WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
[2021-12-09 23:45:09.635] [DEBUG] [CHILD PROCESS OUTPUT]       simplecov_json_formatter (~> 0.1)
[2021-12-09 23:45:09.638] [DEBUG] [CHILD PROCESS OUTPUT]       Available/installed versions of this gem:
[2021-12-09 23:45:09.638] [DEBUG] [CHILD PROCESS OUTPUT]       - 0.1.3
[2021-12-09 23:45:09.638] [DEBUG] [CHILD PROCESS OUTPUT]       - 0.1.2
[2021-12-09 23:45:09.638] [DEBUG] [CHILD PROCESS OUTPUT] WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
[2021-12-09 23:45:09.638] [DEBUG] [CHILD PROCESS OUTPUT] Please report a bug if this causes problems.
[2021-12-09 23:45:10.034] [DEBUG] [CHILD PROCESS OUTPUT] Uncaught exception: cannot load such file -- rspec/core/profiler
[2021-12-09 23:45:10.034] [DEBUG] [CHILD PROCESS OUTPUT] 	/Users/me/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:237:in `require'
```

There is more stack trace but it is just continuation of `cannot load such file`. Is it possible that it is not run with `bundle`? Is  there any way to ensure it runs using bundler?

**Comment by exocode** [comment]
I've the same problem. How can I solve that? 

"SyntaxError: Unexpected end of JSON input"

It only appears when using ruby "debug". regular ruby tests are working

**Comment by JordanC0TT** [comment]
` -- ${process.platform == 'win32' ? '%EXT_DIR%' : '$EXT_DIR'}/debug_rspec.rb ${args}`

**Comment by jimjh** [comment]
Setting `"rubyTestExplorer.debugCommand": "bundle exec rdebug-ide"` resolved this issue for me.

**Comment by navels** [comment]
I will try to make a PR but I don't have the bandwidth at the moment.  Fix is to change this:

https://github.com/connorshea/vscode-ruby-test-adapter/blob/c3ee793cd332306cbe30d9d30363944c8164d3db/src/rspecTests.ts#L191

from

```
  runTestFile = async (testFile: string, debuggerConfig?: vscode.DebugConfiguration) => new Promise<string>(async (resolve, reject) => {
    this.log.info(`Running test file: ${testFile}`);
    const spawnArgs: childProcess.SpawnOptions = {
      cwd: this.workspace.uri.fsPath,
      shell: true
    };
```

to
```
  runTestFile = async (testFile: string, debuggerConfig?: vscode.DebugConfiguration) => new Promise<string>(async (resolve, reject) => {
    this.log.info(`Running test file: ${testFile}`);
    const spawnArgs: childProcess.SpawnOptions = {
      cwd: this.workspace.uri.fsPath,
      shell: true,
      this.getProcessEnv()
    };
```
